# Generated by Django 4.2.22 on 2025-07-28 23:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título da tarefa', max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, help_text='Descrição detalhada da tarefa', null=True, verbose_name='Descrição')),
                ('completed', models.BooleanField(default=False, help_text='Indica se a tarefa foi concluída', verbose_name='Concluída')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Data e hora de criação da tarefa', verbose_name='Criada em')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data e hora da última atualização', verbose_name='Atualizada em')),
            ],
            options={
                'verbose_name': 'Tarefa',
                'verbose_name_plural': 'Tarefas',
                'ordering': ['-created_at'],
            },
        ),
    ]
